name: Dev Build

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: chmod +x gradlew

      - name: Set up Node JS
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Get current dev build number
        id: dev-build
        run: |
          cd .github/devbuilds
          npm install
          echo "number=$(node get_number.js)" >> $GITHUB_ENV

      - name: Build
        run: ./gradlew build -Pcommit=${{ github.sha }} -Pdevbuild=${{ env.number }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-jar
          path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: built-jar
          path: artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: dev-${{ github.run_number }}
          release_name: "Dev Build ${{ github.run_number }}"
          body: "Automated development build from commit ${{ github.sha }}"
          draft: false
          prerelease: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/*.jar
          asset_name: dev-build-${{ github.run_number }}.jar
          asset_content_type: application/java-archive

