name: Dev Build

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  push:
    branches:
      - master
      - workflows

permissions:
  contents: write  # Ensures permissions for creating a release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: chmod +x gradlew

      - name: Build
        run: ./gradlew build -Pcommit=${{ github.sha }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: build/libs/*.jar

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: dev-${{ github.run_number }}
          release_name: "Dev Build ${{ github.run_number }}"
          body: "Development build ${{ github.sha }}"
          draft: false
          prerelease: true

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in build/libs/*.jar; do
            echo "Uploading $file..."
            curl -sSL -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/java-archive" \
              --data-binary @"$file" \
              "${{ steps.create_release.outputs.upload_url }}?name=$(basename "$file")"
          done

