name: Dev Build

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  push:
    branches:
      - master
      - workflows

permissions:
  contents: write  # Ensures permissions for creating a release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: chmod +x gradlew

      - name: Build
        run: ./gradlew build -Pcommit=${{ github.sha }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: build/libs/*.jar

      - name: Create GitHub Release & Upload Assets
        uses: ncipollo/release-action@v1
        with:
          tag: dev-${{ github.run_number }}
          name: "Dev Build ${{ github.run_number }}"
          body: "Development build from commit ${{ github.sha }}"
          prerelease: true
          artifacts: "build/libs/*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
